### ISSUE TITLE
README is empty

### ISSUE THREAD

**Issue by jeremiah** [OpenELEC/iwlwifi-firmware#2]
Is this on purpose?

**Comment by sraue** [comment]
yes, no one added any content, if you want do provide any content

**Comment by jeremiah** [comment]
Sent first draft as a pull request.

**Comment by sraue** [comment]
added in https://github.com/OpenELEC/iwlwifi-firmware/commit/5b563448003ce625ae6988db55b62f24a50bce62 thanks much
